name: Atualizar EPG Diariamente

on:
  schedule:
    # Executa todos os dias às 03:00 UTC (00:00 Horário de Brasília)
    - cron: '0 3 * * *'
  workflow_dispatch: # Permite que você clique em "Run workflow" para testar agora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerar o XML do EPG
        run: python gerar_epg.py

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Adiciona o arquivo específico dentro da pasta
          git add epg/epg_kpoptvbr.xml
          
          git commit -m "EPG Atualizado na pasta: $(date)" || echo "Sem mudanças"
          git push
